jwt:
  key: SK40CSI2PC-D#?4klj50fdl3kd3ldư;l3ke
server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: upload-service
              uri:
                lb://UPLOAD-SERVICE
              predicates:
                - Path=/upload/**

            - id: like-service
              uri:
                lb://LIKE-SERVICE
              predicates:
                - Path=/likes/**

            - id: post-service
              uri:
                lb://POST-SERVICE
              predicates:
                - Path=/posts/**

            - id: comment-service
              uri:
                lb://COMMENT-SERVICE
              predicates:
                - Path=/comments/**
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/

